[package]
name = "lucet-validate"
version = "0.1.0"
description = "Parse and validate webassembly files against witx interface"
homepage = "https://github.com/fastly/lucet"
repository = "https://github.com/fastly/lucet"
license = "Apache-2.0 WITH LLVM-exception"
categories = ["wasm"]
authors = ["Pat Hickey <phickey@fastly.com>"]
edition = "2018"

[lib]
crate-type=["rlib"]

[[bin]]
name = "lucet-validate"
path = "src/main.rs"

[dependencies]
clap = "2"
failure = "0.1"
witx = { git = "https://github.com/webassembly/wasi", branch = "pch/wasi_crate" }
wasi = { git = "https://github.com/webassembly/wasi", branch = "pch/wasi_crate" }
cranelift-entity = { path = "../cranelift/cranelift-entity", version = "0.44.0" }
wasmparser = "0.39.1"


[dev-dependencies]
lucet-wasi-sdk = { path = "../lucet-wasi-sdk", version = "0.1.1" }
tempfile = "3.0"

